export const WEAPONS = [
  {
    name: 'Short Arrow',
    damage: 15,
    blastRadius: 8,
    craterDepth: 2,
    ammo: Infinity,
    color: '#fff',
    description: 'Basic arrow. Unlimited ammo.',
    behavior: 'standard',
  },
  {
    name: 'Spotter Volley',
    damage: 1,
    blastRadius: 2,
    craterDepth: 0.5,
    ammo: Infinity,
    color: '#aaffaa',
    description: 'Fires 5 arrows at spread angles. Great for finding range.',
    behavior: 'tracer',
    elevationOffsets: [0, 5, -5, 10, -10],
  },
  {
    name: 'War Arrow',
    damage: 25,
    blastRadius: 12,
    craterDepth: 3,
    ammo: 10,
    color: '#ff9800',
    description: 'Heavy broadhead. Solid damage.',
    behavior: 'standard',
  },
  {
    name: 'Triple Shot',
    damage: 25,
    blastRadius: 12,
    craterDepth: 3,
    ammo: 3,
    color: '#ff9800',
    description: 'Three arrows at staggered angles.',
    behavior: 'trio',
    elevationOffsets: [0, 3, 6],
  },
  {
    name: 'Ricochet Shot',
    damage: 20,
    blastRadius: 10,
    craterDepth: 2.5,
    ammo: 5,
    color: '#76ff03',
    description: 'Enchanted arrow. Bounces 3 times.',
    behavior: 'bouncer',
    bounces: 3,
    bounceFactor: 0.5,
  },
  {
    name: 'Rolling Stone',
    damage: 25,
    blastRadius: 10,
    craterDepth: 3,
    ammo: 3,
    color: '#ffeb3b',
    description: 'Rolls along terrain on impact.',
    behavior: 'roller',
    rollDuration: 2.0,
  },
  {
    name: 'Mud Ball',
    damage: 5,
    blastRadius: 12,
    craterDepth: -6,
    ammo: 5,
    color: '#8d6e63',
    description: 'Adds terrain instead of removing it. Bury them!',
    behavior: 'standard',
  },
  {
    name: 'Siege Arrow',
    damage: 40,
    blastRadius: 16,
    craterDepth: 5,
    ammo: 5,
    color: '#f44336',
    description: 'Explosive warhead. Big crater.',
    behavior: 'standard',
  },
  {
    name: 'Fire Arrow',
    damage: 8,
    blastRadius: 20,
    craterDepth: 1,
    ammo: 3,
    color: '#ff6f00',
    description: 'Spreads fire over a wide area. Burns for damage.',
    behavior: 'napalm',
    burnDamage: 5,
    burnTicks: 3,
  },
  {
    name: 'Arrow Storm',
    damage: 12,
    blastRadius: 8,
    craterDepth: 2,
    ammo: 3,
    color: '#e040fb',
    description: 'Splits into 8 arrows at peak altitude.',
    behavior: 'mirv',
    submunitions: 8,
    spreadRadius: 10,
  },
  {
    name: 'Burrowing Arrow',
    damage: 30,
    blastRadius: 6,
    craterDepth: 8,
    ammo: 2,
    color: '#00bcd4',
    description: 'Burrows through terrain on impact.',
    behavior: 'tunneler',
    tunnelLength: 20,
  },
  {
    name: "Dragon's Breath",
    damage: 60,
    blastRadius: 30,
    craterDepth: 10,
    ammo: 1,
    color: '#fff',
    description: 'Massive devastation. Handle with care.',
    behavior: 'nuke',
  },
];

export function getWeaponByName(name) {
  return WEAPONS.find(w => w.name === name);
}
