export const WEAPONS = [
  {
    name: 'Short Arrow',
    damage: 15,
    blastRadius: 8,
    craterDepth: 2,
    ammo: Infinity,
    color: '#fff',
    description: 'Basic arrow. Unlimited ammo.',
    behavior: 'standard',
  },
  {
    name: 'Spotter Volley',
    damage: 1,
    blastRadius: 2,
    craterDepth: 0.5,
    ammo: Infinity,
    color: '#aaffaa',
    description: 'Fires 5 arrows at spread angles. Great for finding range.',
    behavior: 'tracer',
    elevationOffsets: [0, 5, -5, 10, -10],
  },
  {
    name: 'War Arrow',
    damage: 25,
    blastRadius: 12,
    craterDepth: 3,
    ammo: 10,
    color: '#ff9800',
    description: 'Heavy broadhead. Solid damage.',
    behavior: 'standard',
  },
  {
    name: 'Triple Shot',
    damage: 25,
    blastRadius: 12,
    craterDepth: 3,
    ammo: 3,
    color: '#ff9800',
    description: 'Three arrows at staggered angles.',
    behavior: 'trio',
    elevationOffsets: [0, 3, 6],
  },
  {
    name: 'Siege Arrow',
    damage: 40,
    blastRadius: 16,
    craterDepth: 5,
    ammo: 5,
    color: '#f44336',
    description: 'Explosive warhead. Big crater.',
    behavior: 'standard',
  },
  {
    name: 'Fire Arrow',
    damage: 8,
    blastRadius: 20,
    craterDepth: 1,
    ammo: 3,
    color: '#ff6f00',
    description: 'Spreads fire over a wide area. Burns for damage.',
    behavior: 'napalm',
    burnDamage: 5,
    burnTicks: 3,
  },
  {
    name: 'Arrow Storm',
    damage: 12,
    blastRadius: 8,
    craterDepth: 2,
    ammo: 3,
    color: '#e040fb',
    description: 'Splits into 8 arrows at peak altitude.',
    behavior: 'mirv',
    submunitions: 8,
    spreadRadius: 10,
  },
  {
    name: 'Blink Arrow',
    damage: 10,
    blastRadius: 6,
    craterDepth: 1,
    ammo: 2,
    color: '#aa00ff',
    description: 'Teleports you to a random distant location on impact.',
    behavior: 'teleport',
  },
  {
    name: 'Sheep Arrow',
    damage: 30,
    blastRadius: 8,
    craterDepth: 2,
    ammo: 2,
    color: '#ffffff',
    description: 'Spawns a ravenous sheep that chases the enemy.',
    behavior: 'sheep',
  },
  {
    name: 'Seed Arrow',
    damage: 5,
    blastRadius: 4,
    craterDepth: 0,
    ammo: 3,
    color: '#4caf50',
    description: 'Grows a cluster of trees where it lands.',
    behavior: 'treegrow',
  },
  {
    name: 'Tempest Arrow',
    damage: 10,
    blastRadius: 6,
    craterDepth: 1,
    ammo: 2,
    color: '#80deea',
    description: 'Creates a persistent tornado that pulls shots toward it.',
    behavior: 'tornado',
  },
  {
    name: "Dragon's Breath",
    damage: 60,
    blastRadius: 30,
    craterDepth: 10,
    ammo: 1,
    color: '#fff',
    description: 'Massive devastation. Handle with care.',
    behavior: 'nuke',
  },
];

export function getWeaponByName(name) {
  return WEAPONS.find(w => w.name === name);
}
